// <auto-generated />
using System;
using MRCModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(HACS_Context))]
    partial class HACS_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("MRCModel.Models.Request", b =>
                {
                    b.Property<int>("requestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("submissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("submittedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("requestId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("MRCModel.Models.User", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MRCModel.Models.AffectedIndividual", b =>
                {
                    b.HasBaseType("MRCModel.Models.User");

                    b.Property<string>("userContactInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("AffectedIndividual");
                });

            modelBuilder.Entity("MRCModel.Models.AidOrganizationWorker", b =>
                {
                    b.HasBaseType("MRCModel.Models.User");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("AidOrganizationWorker");
                });

            modelBuilder.Entity("MRCModel.Models.GovernmentRepresentative", b =>
                {
                    b.HasBaseType("MRCModel.Models.User");

                    b.Property<string>("userAuthorityLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("GovernmentRepresentative");
                });
#pragma warning restore 612, 618
        }
    }
}
